export FABRIC_CFG_PATH=$PWD
export FABRIC_LOGGING_SPEC=ERROR
export ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
export ORDERER_GENERAL_LISTENPORT=7050
export ORDERER_GENERAL_LOCALMSPID=OrdererMSP
export ORDERER_GENERAL_LOCALMSPDIR=./msp
export ORDERER_GENERAL_TLS_ENABLED=true
export ORDERER_GENERAL_TLS_PRIVATEKEY=./tls/server.key
export ORDERER_GENERAL_TLS_CERTIFICATE=./tls/server.crt
export ORDERER_GENERAL_TLS_ROOTCAS=[./tls/ca.crt]
export ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=./tls/server.crt
export ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=./tls/server.key
export ORDERER_GENERAL_CLUSTER_ROOTCAS=[./tls/ca.crt]
export ORDERER_GENERAL_BOOTSTRAPMETHOD=none
export ORDERER_CHANNELPARTICIPATION_ENABLED=true
export ORDERER_ADMIN_TLS_ENABLED=true
export ORDERER_ADMIN_TLS_CERTIFICATE=./tls/server.crt
export ORDERER_ADMIN_TLS_PRIVATEKEY=./tls/server.key
export ORDERER_ADMIN_TLS_ROOTCAS=[./tls/ca.crt]
export ORDERER_ADMIN_TLS_CLIENTROOTCAS=[./tls/ca.crt]
export ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
export ORDERER_OPERATIONS_LISTENADDRESS=orderer1.example.com:9443
export ORDERER_METRICS_PROVIDER=prometheus

killall -9 orderer
./bin/orderer 
