# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer1
        SANS:
          - 10.0.1.136
      - Hostname: orderer2
        SANS:
          - 10.0.1.220
      - Hostname: orderer3
        SANS:
          - 10.0.1.183
      - Hostname: orderer4
        SANS:
          - 10.0.1.214

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true

    Template:
      Count: 1
      SANS:
        - 10.0.1.220
    Users:
      Count: 1
